---
title: "NBID DEG Froze D1 vs D4 FA2 and FA3"
---

```{r setup}
library(NBID)
library(MASS)
library(pscl)
library(nloptr)
# source("./NBID.R")
```

```{r}
D1X_FA2_THA = readRDS("../data/processed_counts/D1X_FA2_THA.rds")
D1X_FA3_THA = readRDS("../data/processed_counts/D1A_FA3_THA.rds")
D4X_FA2_THA = readRDS("../data/processed_counts/D4X_FA2_THA.rds")
D4X_FA3_THA = readRDS("../data/processed_counts/D4X_FA3_THA.rds")
```

```{r}
# filter cells
D1X_FA2_THA = D1X_FA2_THA[,colSums(D1X_FA2_THA)>=4000]
D1X_FA2_THA = D1X_FA2_THA[,colSums(D1X_FA2_THA)<=40000]
D1X_FA3_THA = D1X_FA3_THA[,colSums(D1X_FA3_THA)>=4000]
D1X_FA3_THA = D1X_FA3_THA[,colSums(D1X_FA3_THA)<=40000]
D4X_FA2_THA = D4X_FA2_THA[,colSums(D4X_FA2_THA)>=4000]
D4X_FA2_THA = D4X_FA2_THA[,colSums(D4X_FA2_THA)<=40000]
D4X_FA3_THA = D4X_FA3_THA[,colSums(D4X_FA3_THA)>=4000]
D4X_FA3_THA = D4X_FA3_THA[,colSums(D4X_FA3_THA)<=40000]
```

#FA2 D1 vs D4
```{r}
min.counts = 0
gene.list = Reduce(union,
                   list(
                     rownames(D1X_FA2_THA[rowSums(D1X_FA2_THA) > min.counts, ]),
                   rownames(D4X_FA2_THA[rowSums(D4X_FA2_THA) > min.counts, ])
                   ))
```

```{r}
D1X_FA2_THA.filtered = D1X_FA2_THA[rownames(D1X_FA2_THA) %in% gene.list, ]
D4X_FA2_THA.filtered = D4X_FA2_THA[rownames(D4X_FA2_THA) %in% gene.list, ]
```

```{r}
THA_FA2.data.nocontrol = cbind(
  D1X_FA2_THA.filtered,
  D4X_FA2_THA.filtered
)
group_THA_FA2_no_control = c(rep("D1FA2FROZEN", dim(D1X_FA2_THA.filtered)[2]),
                            rep("D4FA2FROZEN",
                            dim(D4X_FA2_THA.filtered)[2]))
```

```{r}
result = DEUsingNBID(THA_FA2.data.nocontrol, group_THA_FA2_no_control, ncore = 22)
```

```{r}
FDR = p.adjust(result[, "pvalue"], method = "BH")
res_combind = cbind(FDR, result)
res_combind = as.data.frame(res_combind)
res_combind = res_combind[order(res_combind$FDR), ]
res_combind = res_combind[!grepl("^RPS", rownames(res_combind)),]
res_combind = res_combind[!grepl("^RPL", rownames(res_combind)),]
res_combind = res_combind[!grepl("^MT", rownames(res_combind)),]
saveRDS(res_combind, "../data/deg/D1D4_THA_FA2_nocontrol.rds")
write.table(res_combind, "../data/deg/D1D4_THA_FA2_nocontrol.tsv", sep = "\t")

```

```{r}
res_combind = readRDS("../data/deg/D1D4_THA_FA2_nocontrol.rds")

res_combind = res_combind[!grepl("^RPS", rownames(res_combind)),]
res_combind = res_combind[!grepl("^RPL", rownames(res_combind)),]
res_combind = res_combind[!grepl("^MT", rownames(res_combind)),]

res_combind[(res_combind$log2FCD4FA2FROZEN < -10),]$log2FCD4FA2FROZEN = -10
res_combind[(res_combind$log2FCD4FA2FROZEN > 10),]$log2FCD4FA2FROZEN = 10
```


```{r}
# Make a basic volcano plot
with(res_combind, plot(log2FCD4FA2FROZEN, -log10(res_combind$pvalue), pch=20, main="Volcano plot", cex=0.7))

# Add colored points: red if padj<0.05, orange of log2FC>1, green if both)
with(subset(res_combind, FDR<1e-50), points(log2FCD4FA2FROZEN, -log10(pvalue), pch=20, col="red", cex=0.7))
with(subset(res_combind, abs(log2FCD4FA2FROZEN)>1), points(log2FCD4FA2FROZEN, -log10(pvalue), pch=20, col="orange", cex=0.7))
with(subset(res_combind, FDR<1e-50 & abs(log2FCD4FA2FROZEN)>1), points(log2FCD4FA2FROZEN, -log10(pvalue), pch=20, col="green", cex=0.7))

# # Label points with the textxy function from the calibrate plot
# library(calibrate)
# with(subset(res, padj<.05 & abs(log2FoldChange)>1), textxy(log2FoldChange, -log10(pvalue), labs=Gene, cex=.8))

```


# FA2 Highly expressed genes
```{r}
min.counts = 500
gene.list = Reduce(union,
                   list(
                     rownames(D1X_FA2_THA[rowSums(D1X_FA2_THA) > min.counts, ]),
                   rownames(D4X_FA2_THA[rowSums(D4X_FA2_THA) > min.counts, ])
                   ))
```

```{r}
D1X_FA2_THA.filtered = D1X_FA2_THA[rownames(D1X_FA2_THA) %in% gene.list, ]
D4X_FA2_THA.filtered = D4X_FA2_THA[rownames(D4X_FA2_THA) %in% gene.list, ]
```

```{r}
THA_FA2.data.nocontrol = cbind(
  D1X_FA2_THA.filtered,
  D4X_FA2_THA.filtered
)
group_THA_FA2_no_control = c(rep("D1FA2FROZEN", dim(D1X_FA2_THA.filtered)[2]),
                            rep("D4FA2FROZEN",
                            dim(D4X_FA2_THA.filtered)[2]))
```

```{r}
result = DEUsingNBID(THA_FA2.data.nocontrol, group_THA_FA2_no_control, ncore = 22)
```

```{r}
FDR = p.adjust(result[, "pvalue"], method = "BH")
res_combind = cbind(FDR, result)
res_combind = as.data.frame(res_combind)
res_combind = res_combind[order(res_combind$FDR), ]
res_combind = res_combind[!grepl("^RPS", rownames(res_combind)),]
res_combind = res_combind[!grepl("^RPL", rownames(res_combind)),]
res_combind = res_combind[!grepl("^MT", rownames(res_combind)),]
saveRDS(res_combind, "../data/deg/D1D4_THA_FA2_min500_nocontrol.rds")
write.table(res_combind, "../data/deg/D1D4_THA_FA2_min500_nocontrol.tsv", sep = "\t")
```

```{r}
res_combind = readRDS("../data/deg/D1D4_THA_FA2_min500_nocontrol.rds")
res_combind = res_combind[res_combind$FDR<5e-2,]
res_combind = res_combind[!grepl("^RPS", rownames(res_combind)),]
res_combind = res_combind[!grepl("^RPL", rownames(res_combind)),]
res_combind = res_combind[!grepl("^MT", rownames(res_combind)),]
res_combind[(res_combind$log2FCD4FA2FROZEN < -10),]$log2FCD4FA2FROZEN = -10
res_combind[(res_combind$log2FCD4FA2FROZEN > 10),]$log2FCD4FA2FROZEN = 10
```

```{r}
# Make a basic volcano plot
with(res_combind, plot(log2FCD4FA2FROZEN, -log10(res_combind$pvalue), pch=20, main="Volcano plot", cex=0.7))

# Add colored points: red if padj<0.05, orange of log2FC>1, green if both)
with(subset(res_combind, FDR<1e-50), points(log2FCD4FA2FROZEN, -log10(pvalue), pch=20, col="red", cex=0.7))
with(subset(res_combind, abs(log2FCD4FA2FROZEN)>1), points(log2FCD4FA2FROZEN, -log10(pvalue), pch=20, col="orange", cex=0.7))
with(subset(res_combind, FDR<1e-50 & abs(log2FCD4FA2FROZEN)>1), points(log2FCD4FA2FROZEN, -log10(pvalue), pch=20, col="green", cex=0.7))

# # Label points with the textxy function from the calibrate plot
# library(calibrate)
# with(subset(res, padj<.05 & abs(log2FoldChange)>1), textxy(log2FoldChange, -log10(pvalue), labs=Gene, cex=.8))

```


# FA3

#FA3 D1 vs D4
```{r}
min.counts = 0
gene.list = Reduce(union,
                   list(
                     rownames(D1X_FA3_THA[rowSums(D1X_FA3_THA) > min.counts, ]),
                   rownames(D4X_FA3_THA[rowSums(D4X_FA3_THA) > min.counts, ])
                   ))
```

```{r}
D1X_FA3_THA.filtered = D1X_FA3_THA[rownames(D1X_FA3_THA) %in% gene.list, ]
D4X_FA3_THA.filtered = D4X_FA3_THA[rownames(D4X_FA3_THA) %in% gene.list, ]
```

```{r}
THA_FA3.data.nocontrol = cbind(
  D1X_FA3_THA.filtered,
  D4X_FA3_THA.filtered
)
group_THA_FA3_no_control = c(rep("D1FA3FROZEN", dim(D1X_FA3_THA.filtered)[2]),
                            rep("D4FA3FROZEN",
                            dim(D4X_FA3_THA.filtered)[2]))
```

```{r}
result = DEUsingNBID(THA_FA3.data.nocontrol, group_THA_FA3_no_control, ncore = 22)
```

```{r}
FDR = p.adjust(result[, "pvalue"], method = "BH")
res_combind = cbind(FDR, result)
res_combind = as.data.frame(res_combind)
res_combind = res_combind[order(res_combind$FDR), ]
res_combind = res_combind[!grepl("^RPS", rownames(res_combind)),]
res_combind = res_combind[!grepl("^RPL", rownames(res_combind)),]
res_combind = res_combind[!grepl("^MT", rownames(res_combind)),]
saveRDS(res_combind, "../data/deg/D1D4_THA_FA3_nocontrol.rds")
write.table(res_combind, "../data/deg/D1D4_THA_FA3_nocontrol.tsv", sep = "\t")

```

```{r}
res_combind = readRDS("../data/deg/D1D4_THA_FA3_nocontrol.rds")

res_combind = res_combind[!grepl("^RPS", rownames(res_combind)),]
res_combind = res_combind[!grepl("^RPL", rownames(res_combind)),]
res_combind = res_combind[!grepl("^MT", rownames(res_combind)),]

res_combind[(res_combind$log2FCD4FA3FROZEN < -10),]$log2FCD4FA3FROZEN = -10
res_combind[(res_combind$log2FCD4FA3FROZEN > 10),]$log2FCD4FA3FROZEN = 10
```


```{r}
# Make a basic volcano plot
with(res_combind, plot(log2FCD4FA3FROZEN, -log10(res_combind$pvalue), pch=20, main="Volcano plot", cex=0.7))

# Add colored points: red if padj<0.05, orange of log2FC>1, green if both)
with(subset(res_combind, FDR<1e-50), points(log2FCD4FA3FROZEN, -log10(pvalue), pch=20, col="red", cex=0.7))
with(subset(res_combind, abs(log2FCD4FA3FROZEN)>1), points(log2FCD4FA3FROZEN, -log10(pvalue), pch=20, col="orange", cex=0.7))
with(subset(res_combind, FDR<1e-50 & abs(log2FCD4FA3FROZEN)>1), points(log2FCD4FA3FROZEN, -log10(pvalue), pch=20, col="green", cex=0.7))

# # Label points with the textxy function from the calibrate plot
# library(calibrate)
# with(subset(res, padj<.05 & abs(log2FoldChange)>1), textxy(log2FoldChange, -log10(pvalue), labs=Gene, cex=.8))

```


# FA3 Highly expressed genes
```{r}
min.counts = 500
gene.list = Reduce(union,
                   list(
                     rownames(D1X_FA3_THA[rowSums(D1X_FA3_THA) > min.counts, ]),
                   rownames(D4X_FA3_THA[rowSums(D4X_FA3_THA) > min.counts, ])
                   ))
```

```{r}
D1X_FA3_THA.filtered = D1X_FA3_THA[rownames(D1X_FA3_THA) %in% gene.list, ]
D4X_FA3_THA.filtered = D4X_FA3_THA[rownames(D4X_FA3_THA) %in% gene.list, ]
```

```{r}
THA_FA3.data.nocontrol = cbind(
  D1X_FA3_THA.filtered,
  D4X_FA3_THA.filtered
)
group_THA_FA3_no_control = c(rep("D1FA3FROZEN", dim(D1X_FA3_THA.filtered)[2]),
                            rep("D4FA3FROZEN",
                            dim(D4X_FA3_THA.filtered)[2]))
```

```{r}
result = DEUsingNBID(THA_FA3.data.nocontrol, group_THA_FA3_no_control, ncore = 22)
```

```{r}
FDR = p.adjust(result[, "pvalue"], method = "BH")
res_combind = cbind(FDR, result)
res_combind = as.data.frame(res_combind)
res_combind = res_combind[order(res_combind$FDR), ]
res_combind = res_combind[!grepl("^RPS", rownames(res_combind)),]
res_combind = res_combind[!grepl("^RPL", rownames(res_combind)),]
res_combind = res_combind[!grepl("^MT", rownames(res_combind)),]
saveRDS(res_combind, "../data/deg/D1D4_THA_FA3_min500_nocontrol.rds")
write.table(res_combind, "../data/deg/D1D4_THA_FA3_min500_nocontrol.tsv", sep = "\t")
```

```{r}
res_combind = readRDS("../data/deg/D1D4_THA_FA3_min500_nocontrol.rds")
res_combind = res_combind[res_combind$FDR<5e-2,]
res_combind = res_combind[!grepl("^RPS", rownames(res_combind)),]
res_combind = res_combind[!grepl("^RPL", rownames(res_combind)),]
res_combind = res_combind[!grepl("^MT", rownames(res_combind)),]
res_combind[(res_combind$log2FCD4FA3FROZEN < -10),]$log2FCD4FA3FROZEN = -10
res_combind[(res_combind$log2FCD4FA3FROZEN > 10),]$log2FCD4FA3FROZEN = 10
```

```{r}
# Make a basic volcano plot
with(res_combind, plot(log2FCD4FA3FROZEN, -log10(res_combind$pvalue), pch=20, main="Volcano plot", cex=0.7))

# Add colored points: red if padj<0.05, orange of log2FC>1, green if both)
with(subset(res_combind, FDR<1e-50), points(log2FCD4FA3FROZEN, -log10(pvalue), pch=20, col="red", cex=0.7))
with(subset(res_combind, abs(log2FCD4FA3FROZEN)>1), points(log2FCD4FA3FROZEN, -log10(pvalue), pch=20, col="orange", cex=0.7))
with(subset(res_combind, FDR<1e-50 & abs(log2FCD4FA3FROZEN)>1), points(log2FCD4FA3FROZEN, -log10(pvalue), pch=20, col="green", cex=0.7))

# # Label points with the textxy function from the calibrate plot
# library(calibrate)
# with(subset(res, padj<.05 & abs(log2FoldChange)>1), textxy(log2FoldChange, -log10(pvalue), labs=Gene, cex=.8))

```
